[ログ設計・実装(ログファイルにホスト名を入れれるようにERB通す)] bin/tenginedのrunのブロックの中で@__config__.dupすると以下の例外が発生するので、dupしないように修正しました
[NameError] undefined local variable or method `application_log' for #<Tengine::Core::Config::Core:0x007fc8692b4718>
  /Users/akima/.rvm/gems/ruby-1.9.2-head@tengine_console/gems/tengine_core-0.4.0/lib/tengine/core/config/core.rb:293:in `setup_loggers'
  /Users/akima/.rvm/gems/ruby-1.9.2-head@tengine_console/gems/tengine_core-0.4.0/bin/tengined:151:in `block in <top (required)>'
  /Users/akima/.rvm/gems/ruby-1.9.2-head@tengine_console/gems/tengine_core-0.4.0/bin/tengined:93:in `chdir'